Traceback (most recent call last):
  File "C:\Users\miaha\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\miaha\anaconda3\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\miaha\anaconda3\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\miaha\anaconda3\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\miaha\anaconda3\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\miaha\anaconda3\lib\site-packages\nbclient\client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "C:\Users\miaha\anaconda3\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\Users\miaha\anaconda3\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
create_wordclouds(anakin_dict)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_2976/1899327667.py[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [0mcreate_wordclouds[0m[1;33m([0m[0manakin_dict[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m
[1;32m~\AppData\Local\Temp/ipykernel_2976/2765383741.py[0m in [0;36mcreate_wordclouds[1;34m(data)[0m
[0;32m     27[0m     [1;31m#Create wordclouds[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[0;32m     28[0m     [0mcol_word[0m [1;33m=[0m [1;33m[[0m[1;34m'Reds'[0m[1;33m,[0m [1;34m'Purples'[0m[1;33m,[0m [1;34m'BuGn'[0m[1;33m,[0m [1;34m'Blues'[0m[1;33m,[0m [1;34m'Greens'[0m[1;33m][0m [1;31m#Colormap[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 29[1;33m     [0mmask[0m [1;33m=[0m [0mnp[0m[1;33m.[0m[0marray[0m[1;33m([0m[0mImage[0m[1;33m.[0m[0mopen[0m[1;33m([0m[0mos[0m[1;33m.[0m[0mgetcwd[0m[1;33m([0m[1;33m)[0m [1;33m+[0m [1;34m'/data/Stormtrooper.jpg'[0m[1;33m)[0m[1;33m)[0m [1;31m#Create shape image for wordclouds[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     30[0m     [0ma[0m [1;33m=[0m [1;36m0[0m[1;33m[0m[1;33m[0m[0m
[0;32m     31[0m [1;33m[0m[0m

[1;31mNameError[0m: name 'Image' is not defined
NameError: name 'Image' is not defined

